import type { ReactNode } from "react";
import type { Metadata } from "next"
import { Inter, Nanum_Gothic } from "next/font/google"

import "./globals.css";

const inter = Inter({ subsets: ["latin"] })
const nanumGothic = Nanum_Gothic({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
  variable: '--nanum-gothic'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${nanumGothic.variable}`}>{children}</body>
    </html>
  );
}
